# Generated by Django 4.2 on 2026-04-21 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="What skill are you offering?", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Describe your skill in detail"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tutoring", "Tutoring"),
                            ("music", "Music Lessons"),
                            ("sports", "Sports"),
                            ("tech", "Tech Help"),
                            ("art", "Art & Design"),
                            ("writing", "Writing"),
                            ("language", "Language"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[("free", "Free"), ("paid", "Paid")],
                        default="free",
                        max_length=10,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave blank if offering for free",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("available", "Available Now"),
                            ("weekends", "Weekends Only"),
                            ("limited", "Limited Availability"),
                            ("unavailable", "Currently Unavailable"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "contact_preference",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("inperson", "In Person"),
                            ("online", "Online"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Skills",
                "ordering": ["-created_at"],
            },
        ),
    ]
