# Generated by Django 4.2 on 2026-04-23 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "⭐ Poor"),
                            (2, "⭐⭐ Fair"),
                            (3, "⭐⭐⭐ Good"),
                            (4, "⭐⭐⭐⭐ Very Good"),
                            (5, "⭐⭐⭐⭐⭐ Excellent"),
                        ],
                        default=5,
                        help_text="Rate this skill from 1 to 5 stars",
                    ),
                ),
                (
                    "review_text",
                    models.TextField(
                        help_text="Share your experience with this skill",
                        max_length=1000,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("skill", "reviewer")},
            },
        ),
    ]
